CREATE TABLE IF NOT EXISTS study_comment (
    scid       BIGINT AUTO_INCREMENT PRIMARY KEY,
    isid       BIGINT  NOT NULL,
    user_id    BIGINT  NOT NULL,
    content    TEXT    NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (isid)    REFERENCES investment_study(isid) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user_account(user_id)  ON DELETE CASCADE
);
